version: "3.7"

services:
  sistema:
    image: webdevops/php-apache:alpine-php7
    ports:
      - "8081:80"
    volumes:
      - /data/projetoweb/:/app

    networks:
      - devops

  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "Senha123"
      MYSQL_DATABASE: "testedb"
    ports:
      - "3306:3306"
    volumes:
      - /data/mysql-C:/var/lib/mysql
    networks:
      - devops


networks:
  devops:
    driver: bridge

